version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../
      dockerfile: Dockerfile    
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/recepies/

    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    #image: ruslgl/frontend:v1
    build:
      context: ../frontend
      dockerfile: Dockerfile

    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/recepies/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - db
    restart: always


volumes:
  postgres_data:
  static_value:
  media_value: