# Generated by Django 2.2.16 on 2022-12-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0004_auto_20221214_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
